// <auto-generated />
namespace WebApi_Net60.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialMigraton : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialMigraton));
        
        string IMigrationMetadata.Id
        {
            get { return "202111270926366_initialMigraton"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
